apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "perfomax-be.fullname" . }}
  labels:
    {{- include "perfomax-be.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "perfomax-be.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "perfomax-be.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "perfomax-be.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60  # Time to wait before starting the probe after the container starts
            timeoutSeconds: 10        # Time for each probe to wait for a response
            periodSeconds: 20        # Frequency of the probe checks
            failureThreshold: 3      # Number of failed probes before the container is restarted
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          env:
          {{- $fullName := include "perfomax-be.fullname" . -}}
          {{- range .Values.secrets }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name:  {{ $fullName }}-secrets
                  key: {{ . }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
