apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "perfomax-be.name" . }}
spec:
  refreshInterval: "10m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store
  target:
    name: {{ include "perfomax-be.name" . }}-secrets
    creationPolicy: Owner
  data:
  {{- $chartName := .Chart.Name }}
  {{- range .Values.secrets }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.env.name }}/perfomax/apps/backend
        property: {{ . }}
  {{- end }}